CREATE TABLE IF NOT EXISTS roles (id SERIAL PRIMARY KEY, name VARCHAR(32) UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS user_roles (user_id INT NOT NULL, role_id INT NOT NULL);
CREATE TABLE IF NOT EXISTS operation_logs (id SERIAL PRIMARY KEY, actor_id INT, action VARCHAR(128), detail TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT INTO roles(name) VALUES ('user'), ('lawyer'), ('admin') ON CONFLICT DO NOTHING;

