CREATE TABLE IF NOT EXISTS roles (id SERIAL PRIMARY KEY, name VARCHAR(32) UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS user_roles (user_id INT NOT NULL, role_id INT NOT NULL);
CREATE TABLE IF NOT EXISTS operation_logs (id SERIAL PRIMARY KEY, actor_id INT, action VARCHAR(128), detail TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, email VARCHAR(128) UNIQUE NOT NULL, password_hash VARCHAR(256) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS documents (id SERIAL PRIMARY KEY, user_id INT NOT NULL, title VARCHAR(256) NOT NULL, file_type VARCHAR(32) NOT NULL, file_size INT DEFAULT 0, content TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS review_tasks (id SERIAL PRIMARY KEY, document_id INT NOT NULL, user_id INT NOT NULL, status VARCHAR(32) DEFAULT 'pending', risk_level VARCHAR(32) DEFAULT 'none', summary TEXT DEFAULT '', completed_at TIMESTAMP, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS risk_items (id SERIAL PRIMARY KEY, review_task_id INT NOT NULL, clause_type VARCHAR(32) DEFAULT 'other', risk_level VARCHAR(32) DEFAULT 'low', review_status VARCHAR(32) DEFAULT 'pending', description TEXT, suggestion TEXT, start_pos INT DEFAULT 0, end_pos INT DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, reviewed_at TIMESTAMP);
INSERT INTO roles(name) VALUES ('user'), ('lawyer'), ('admin') ON CONFLICT DO NOTHING;

