ERROR_CODES = {
    "AUTH_INVALID": "AUTH_INVALID",
    "DOCUMENT_UNSUPPORTED": "DOCUMENT_UNSUPPORTED",
    "DOCUMENT_TOO_LARGE": "DOCUMENT_TOO_LARGE",
    "REVIEW_FAILED": "REVIEW_FAILED",
    "RISK_LEVEL_HIGH": "RISK_LEVEL_HIGH",
    "CLAUSE_TYPE_UNKNOWN": "CLAUSE_TYPE_UNKNOWN",
}

