LOG_TEMPLATES = {
    "USER_REGISTER": "User[email={email}] register role={role}",
    "USER_LOGIN": "User[email={email}] login",
    "USER_QUOTA_READ": "User[id={id}] quota read",
    "DOCUMENT_UPLOAD": "Document[title={title},file_type={file_type}] upload by role={role}",
    "DOCUMENT_UPLOAD_FAILED": "Document[title={title}] upload failed: {reason}",
    "DOCUMENT_STATUS": "Document[id={id}] status read",
    "DOCUMENT_PARSE_START": "Document[id={id},file_type={file_type}] parse start",
    "DOCUMENT_PARSE_DONE": "Document[id={id}] parse done",
    "DOCUMENT_PARSE_FAILED": "Document[id={id}] parse failed: {reason}",
    "REVIEW_CREATE": "ReviewTask[document_id={document_id}] create by role={role}",
    "REVIEW_RETRY": "ReviewTask[id={id}] retry",
    "REVIEW_DONE": "ReviewTask[id={id},risk_level={risk_level}] done",
    "REVIEW_FAILED": "ReviewTask[id={id}] failed: {reason}",
    "RISK_ITEM_CREATE": "RiskItem[clause_type={clause_type},risk_level={risk_level}] create",
    "RISK_ITEM_UPDATE": "RiskItem[id={risk_item_id}] update status={review_status}",
    "RISK_ITEM_FILTER": "RiskItem[review_task_id={review_task_id}] filter {clause_type}/{risk_level}",
    "REPORT_EXPORT": "Report[review_id={review_id}] export",
    "REPORT_EXPORT_FAILED": "Report[review_id={review_id}] export failed: {reason}",
    "AUTH_REQUIRED": "Auth required path={path}",
    "RBAC_DENY": "RBAC role={role} path={path} deny",
    "RATE_LIMIT_HIT": "Rate limit key={key} hit",
    "AUDIT_WRITE": "Audit[action={action}] actor={actor_id}",
    "MIDDLEWARE_ERROR": "Middleware[name={name}] error={error}",
    "DB_CONNECT": "Database[url={url}] connect",
    "DB_QUERY_FAILED": "Database[entity={entity}] query failed: {reason}",
    "FILE_VALIDATE": "File[name={name},size={size}] validate",
    "FILE_VALIDATE_FAILED": "File[name={name}] validate failed: {reason}",
    "TEXT_EXTRACT": "TextExtractor[file_type={file_type}] extract",
    "PASSWORD_HASH": "User[email={email}] password hash",
    "JWT_SIGN": "JWT[user_id={user_id},role={role}] sign",
    "JWT_VERIFY": "JWT verify",
    "CELERY_SUBMIT": "Celery[review_task_id={review_task_id}] submit",
    "CELERY_DONE": "Celery[review_task_id={review_task_id}] done",
}

